Repository bazelbuild/bazel-central-registry, pull requests merged in 2025-09, with the labels that each got.

#5700 boost.container_hash@1.89.0
  modules/boost.container_hash/1.89.0/MODULE.bazel
  modules/boost.container_hash/1.89.0/overlay/BUILD.bazel
  modules/boost.container_hash/1.89.0/overlay/MODULE.bazel
  modules/boost.container_hash/1.89.0/presubmit.yml
  modules/boost.container_hash/1.89.0/source.json
  modules/boost.container_hash/metadata.json
  modules/boost.intrusive/1.89.0/MODULE.bazel
  modules/boost.intrusive/1.89.0/overlay/BUILD.bazel
  modules/boost.intrusive/1.89.0/overlay/MODULE.bazel
  modules/boost.intrusive/1.89.0/presubmit.yml
  modules/boost.intrusive/1.89.0/source.json
  modules/boost.intrusive/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check, skip-compatibility-level-check

#5733 boost.system@1.89.0
  modules/boost.system/1.89.0/MODULE.bazel
  modules/boost.system/1.89.0/overlay/BUILD.bazel
  modules/boost.system/1.89.0/overlay/MODULE.bazel
  modules/boost.system/1.89.0/presubmit.yml
  modules/boost.system/1.89.0/source.json
  modules/boost.system/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5716 boost.detail@1.89.0
  modules/boost.detail/1.89.0/MODULE.bazel
  modules/boost.detail/1.89.0/overlay/BUILD.bazel
  modules/boost.detail/1.89.0/overlay/MODULE.bazel
  modules/boost.detail/1.89.0/overlay/test/BUILD.bazel
  modules/boost.detail/1.89.0/overlay/test/MODULE.bazel
  modules/boost.detail/1.89.0/presubmit.yml
  modules/boost.detail/1.89.0/source.json
  modules/boost.detail/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5730 boost.hash2@1.89.0
  modules/boost.hash2/1.89.0/MODULE.bazel
  modules/boost.hash2/1.89.0/overlay/BUILD.bazel
  modules/boost.hash2/1.89.0/overlay/MODULE.bazel
  modules/boost.hash2/1.89.0/overlay/test/BUILD.bazel
  modules/boost.hash2/1.89.0/overlay/test/MODULE.bazel
  modules/boost.hash2/1.89.0/presubmit.yml
  modules/boost.hash2/1.89.0/source.json
  modules/boost.hash2/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5717 feat(blake3): Add version 1.8.2 with optional oneTBB support
  modules/blake3/1.8.2/MODULE.bazel
  modules/blake3/1.8.2/overlay/BUILD.bazel
  modules/blake3/1.8.2/overlay/MODULE.bazel
  modules/blake3/1.8.2/overlay/c/BUILD.bazel
  modules/blake3/1.8.2/presubmit.yml
  modules/blake3/1.8.2/source.json
  modules/blake3/README.md
  modules/blake3/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check

#5663 Add contrib_rules_jvm 0.30.0
  modules/contrib_rules_jvm/0.30.0/MODULE.bazel
  modules/contrib_rules_jvm/0.30.0/patches/0001-Prepare-for-future-Bazel-releases-363.patch
  modules/contrib_rules_jvm/0.30.0/patches/update-version.patch
  modules/contrib_rules_jvm/0.30.0/presubmit.yml
  modules/contrib_rules_jvm/0.30.0/source.json
  modules/contrib_rules_jvm/metadata.json
Labels: presubmit-auto-run, skip-incompatible-flags-test

#5690 Publish rules_tensorrt_rtx@0.1.0
  modules/rules_tensorrt_rtx/0.1.0/MODULE.bazel
  modules/rules_tensorrt_rtx/0.1.0/attestations.json
  modules/rules_tensorrt_rtx/0.1.0/presubmit.yml
  modules/rules_tensorrt_rtx/0.1.0/source.json
  modules/rules_tensorrt_rtx/metadata.json
Labels: presubmit-auto-run

#5694 hermetic_clang_toolchain@1.0.0
  modules/hermetic_clang_toolchain/1.0.0/MODULE.bazel
  modules/hermetic_clang_toolchain/1.0.0/presubmit.yml
  modules/hermetic_clang_toolchain/1.0.0/source.json
  modules/hermetic_clang_toolchain/metadata.json
Labels: presubmit-auto-run

#5745 boost.any@1.89.0
  modules/boost.any/1.89.0/MODULE.bazel
  modules/boost.any/1.89.0/overlay/BUILD.bazel
  modules/boost.any/1.89.0/overlay/MODULE.bazel
  modules/boost.any/1.89.0/presubmit.yml
  modules/boost.any/1.89.0/source.json
  modules/boost.any/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5753 boost.mpl@1.89.0
  modules/boost.mpl/1.89.0/MODULE.bazel
  modules/boost.mpl/1.89.0/overlay/BUILD.bazel
  modules/boost.mpl/1.89.0/overlay/MODULE.bazel
  modules/boost.mpl/1.89.0/presubmit.yml
  modules/boost.mpl/1.89.0/source.json
  modules/boost.mpl/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5751 boost.function@1.89.0
  modules/boost.function/1.89.0/MODULE.bazel
  modules/boost.function/1.89.0/overlay/BUILD.bazel
  modules/boost.function/1.89.0/overlay/MODULE.bazel
  modules/boost.function/1.89.0/presubmit.yml
  modules/boost.function/1.89.0/source.json
  modules/boost.function/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5750 boost.format@1.89.0
  modules/boost.format/1.89.0/MODULE.bazel
  modules/boost.format/1.89.0/overlay/BUILD.bazel
  modules/boost.format/1.89.0/overlay/MODULE.bazel
  modules/boost.format/1.89.0/presubmit.yml
  modules/boost.format/1.89.0/source.json
  modules/boost.format/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5748 boost.dynamic_bitset@1.89.0
  modules/boost.dynamic_bitset/1.89.0/MODULE.bazel
  modules/boost.dynamic_bitset/1.89.0/overlay/BUILD.bazel
  modules/boost.dynamic_bitset/1.89.0/overlay/MODULE.bazel
  modules/boost.dynamic_bitset/1.89.0/presubmit.yml
  modules/boost.dynamic_bitset/1.89.0/source.json
  modules/boost.dynamic_bitset/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5757 boost.static_string@1.89.0
  modules/boost.static_string/1.89.0/MODULE.bazel
  modules/boost.static_string/1.89.0/overlay/BUILD.bazel
  modules/boost.static_string/1.89.0/overlay/MODULE.bazel
  modules/boost.static_string/1.89.0/presubmit.yml
  modules/boost.static_string/1.89.0/source.json
  modules/boost.static_string/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5756 boost.rational@1.89.0
  modules/boost.rational/1.89.0/MODULE.bazel
  modules/boost.rational/1.89.0/overlay/BUILD.bazel
  modules/boost.rational/1.89.0/overlay/MODULE.bazel
  modules/boost.rational/1.89.0/presubmit.yml
  modules/boost.rational/1.89.0/source.json
  modules/boost.rational/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5747 boost.conversion@1.89.0
  modules/boost.conversion/1.89.0/MODULE.bazel
  modules/boost.conversion/1.89.0/overlay/BUILD.bazel
  modules/boost.conversion/1.89.0/overlay/MODULE.bazel
  modules/boost.conversion/1.89.0/presubmit.yml
  modules/boost.conversion/1.89.0/source.json
  modules/boost.conversion/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5742 Publish aspect_rules_lint@1.7.0
  modules/aspect_rules_lint/1.7.0/MODULE.bazel
  modules/aspect_rules_lint/1.7.0/attestations.json
  modules/aspect_rules_lint/1.7.0/patches/go_dev_deps.patch
  modules/aspect_rules_lint/1.7.0/patches/module_dot_bazel_version.patch
  modules/aspect_rules_lint/1.7.0/presubmit.yml
  modules/aspect_rules_lint/1.7.0/source.json
  modules/aspect_rules_lint/metadata.json
Labels: skip-incompatible-flags-test

#5759 boost.stacktrace@1.89.0
  modules/boost.stacktrace/1.89.0/MODULE.bazel
  modules/boost.stacktrace/1.89.0/overlay/BUILD.bazel
  modules/boost.stacktrace/1.89.0/overlay/MODULE.bazel
  modules/boost.stacktrace/1.89.0/presubmit.yml
  modules/boost.stacktrace/1.89.0/source.json
  modules/boost.stacktrace/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5758 Bump deps
  MODULE.bazel
Labels: presubmit-auto-run

#5764 boost.context@1.89.0
  modules/boost.context/1.89.0/MODULE.bazel
  modules/boost.context/1.89.0/overlay/BUILD.bazel
  modules/boost.context/1.89.0/overlay/MODULE.bazel
  modules/boost.context/1.89.0/presubmit.yml
  modules/boost.context/1.89.0/source.json
  modules/boost.context/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5726 Publish gcc_toolchain@0.9.0
  modules/gcc_toolchain/0.9.0/MODULE.bazel
  modules/gcc_toolchain/0.9.0/attestations.json
  modules/gcc_toolchain/0.9.0/patches/module_dot_bazel_version.patch
  modules/gcc_toolchain/0.9.0/presubmit.yml
  modules/gcc_toolchain/0.9.0/source.json
  modules/gcc_toolchain/metadata.json
Labels: presubmit-auto-run

#5774 boost.scope_exit@1.89.0
  modules/boost.scope_exit/1.89.0/MODULE.bazel
  modules/boost.scope_exit/1.89.0/overlay/BUILD.bazel
  modules/boost.scope_exit/1.89.0/overlay/MODULE.bazel
  modules/boost.scope_exit/1.89.0/presubmit.yml
  modules/boost.scope_exit/1.89.0/source.json
  modules/boost.scope_exit/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5778 boost.random@1.89.0
  modules/boost.random/1.89.0/MODULE.bazel
  modules/boost.random/1.89.0/overlay/BUILD.bazel
  modules/boost.random/1.89.0/overlay/MODULE.bazel
  modules/boost.random/1.89.0/presubmit.yml
  modules/boost.random/1.89.0/source.json
  modules/boost.random/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5776 boost.coroutine@1.89.0
  modules/boost.coroutine/1.89.0/MODULE.bazel
  modules/boost.coroutine/1.89.0/overlay/BUILD.bazel
  modules/boost.coroutine/1.89.0/overlay/MODULE.bazel
  modules/boost.coroutine/1.89.0/presubmit.yml
  modules/boost.coroutine/1.89.0/source.json
  modules/boost.coroutine/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5775 boost.variant@1.89.0
  modules/boost.variant/1.89.0/MODULE.bazel
  modules/boost.variant/1.89.0/overlay/BUILD.bazel
  modules/boost.variant/1.89.0/overlay/MODULE.bazel
  modules/boost.variant/1.89.0/presubmit.yml
  modules/boost.variant/1.89.0/source.json
  modules/boost.variant/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5782 boost.lexical_cast@1.89.0
  modules/boost.lexical_cast/1.89.0/MODULE.bazel
  modules/boost.lexical_cast/1.89.0/overlay/BUILD.bazel
  modules/boost.lexical_cast/1.89.0/overlay/MODULE.bazel
  modules/boost.lexical_cast/1.89.0/presubmit.yml
  modules/boost.lexical_cast/1.89.0/source.json
  modules/boost.lexical_cast/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5762 boost.chrono@1.89.0
  modules/boost.chrono/1.89.0/MODULE.bazel
  modules/boost.chrono/1.89.0/overlay/BUILD.bazel
  modules/boost.chrono/1.89.0/overlay/MODULE.bazel
  modules/boost.chrono/1.89.0/presubmit.yml
  modules/boost.chrono/1.89.0/source.json
  modules/boost.chrono/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5761 boost.interprocess@1.89.0
  modules/boost.interprocess/1.89.0/MODULE.bazel
  modules/boost.interprocess/1.89.0/overlay/BUILD.bazel
  modules/boost.interprocess/1.89.0/overlay/MODULE.bazel
  modules/boost.interprocess/1.89.0/presubmit.yml
  modules/boost.interprocess/1.89.0/source.json
  modules/boost.interprocess/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5752 boost.json@1.89.0
  modules/boost.json/1.89.0/MODULE.bazel
  modules/boost.json/1.89.0/overlay/BUILD.bazel
  modules/boost.json/1.89.0/overlay/MODULE.bazel
  modules/boost.json/1.89.0/overlay/boost.json.cpp
  modules/boost.json/1.89.0/presubmit.yml
  modules/boost.json/1.89.0/source.json
  modules/boost.json/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5784 boost.tokenizer@1.89.0
  modules/boost.tokenizer/1.89.0/MODULE.bazel
  modules/boost.tokenizer/1.89.0/overlay/BUILD.bazel
  modules/boost.tokenizer/1.89.0/overlay/MODULE.bazel
  modules/boost.tokenizer/1.89.0/presubmit.yml
  modules/boost.tokenizer/1.89.0/source.json
  modules/boost.tokenizer/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5787 boost.regex@1.89.0
  modules/boost.regex/1.89.0/MODULE.bazel
  modules/boost.regex/1.89.0/overlay/BUILD.bazel
  modules/boost.regex/1.89.0/overlay/MODULE.bazel
  modules/boost.regex/1.89.0/presubmit.yml
  modules/boost.regex/1.89.0/source.json
  modules/boost.regex/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5786 boost.range@1.89.0
  modules/boost.range/1.89.0/MODULE.bazel
  modules/boost.range/1.89.0/overlay/BUILD.bazel
  modules/boost.range/1.89.0/overlay/MODULE.bazel
  modules/boost.range/1.89.0/presubmit.yml
  modules/boost.range/1.89.0/source.json
  modules/boost.range/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5792 boost.algorithm@1.89.0
  modules/boost.algorithm/1.89.0/MODULE.bazel
  modules/boost.algorithm/1.89.0/overlay/BUILD.bazel
  modules/boost.algorithm/1.89.0/overlay/MODULE.bazel
  modules/boost.algorithm/1.89.0/presubmit.yml
  modules/boost.algorithm/1.89.0/source.json
  modules/boost.algorithm/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5794 boost.asio@1.89.0
  modules/boost.asio/1.89.0/MODULE.bazel
  modules/boost.asio/1.89.0/overlay/BUILD.bazel
  modules/boost.asio/1.89.0/overlay/MODULE.bazel
  modules/boost.asio/1.89.0/overlay/test/BUILD.bazel
  modules/boost.asio/1.89.0/overlay/test/MODULE.bazel
  modules/boost.asio/1.89.0/overlay/test/archetypes/BUILD.bazel
  modules/boost.asio/1.89.0/presubmit.yml
  modules/boost.asio/1.89.0/source.json
  modules/boost.asio/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5785 boost.program_options@1.89.0
  modules/boost.program_options/1.89.0/MODULE.bazel
  modules/boost.program_options/1.89.0/overlay/BUILD.bazel
  modules/boost.program_options/1.89.0/overlay/MODULE.bazel
  modules/boost.program_options/1.89.0/overlay/test/BUILD.bazel
  modules/boost.program_options/1.89.0/overlay/test/MODULE.bazel
  modules/boost.program_options/1.89.0/presubmit.yml
  modules/boost.program_options/1.89.0/source.json
  modules/boost.program_options/metadata.json
Labels: skip-url-stability-check, auto-merged, skip-compatibility-level-check

#5777 boost.coroutine2@1.89.0
  modules/boost.coroutine2/1.89.0/MODULE.bazel
  modules/boost.coroutine2/1.89.0/overlay/BUILD.bazel
  modules/boost.coroutine2/1.89.0/overlay/MODULE.bazel
  modules/boost.coroutine2/1.89.0/presubmit.yml
  modules/boost.coroutine2/1.89.0/source.json
  modules/boost.coroutine2/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check, skip-compatibility-level-check

#5834 feat(LZ4): Add version 1.10.0 with optional multithreaded CLI support
  modules/lz4/1.10.0/MODULE.bazel
  modules/lz4/1.10.0/overlay/BUILD.bazel
  modules/lz4/1.10.0/overlay/MODULE.bazel
  modules/lz4/1.10.0/overlay/programs/BUILD.bazel
  modules/lz4/1.10.0/presubmit.yml
  modules/lz4/1.10.0/source.json
  modules/lz4/README.md
  modules/lz4/metadata.json
Labels: presubmit-auto-run

#5879 Add grpc-java 1.73.0
  modules/grpc-java/1.73.0/MODULE.bazel
  modules/grpc-java/1.73.0/patches/module_dot_bazel.patch
  modules/grpc-java/1.73.0/presubmit.yml
  modules/grpc-java/1.73.0/source.json
  modules/grpc-java/metadata.json
Labels: skip-url-stability-check, skip-incompatible-flags-test

#5866 feat: add `nonstd-span`
  modules/nonstd-span/0.11.0/MODULE.bazel
  modules/nonstd-span/0.11.0/overlay/BUILD.bazel
  modules/nonstd-span/0.11.0/overlay/MODULE.bazel
  modules/nonstd-span/0.11.0/presubmit.yml
  modules/nonstd-span/0.11.0/source.json
  modules/nonstd-span/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check

#5856 grpc_kotlin@1.5.0-rc.5
  modules/grpc_kotlin/1.5.0-rc.5/MODULE.bazel
  modules/grpc_kotlin/1.5.0-rc.5/patches/module_dot_bazel_version.patch
  modules/grpc_kotlin/1.5.0-rc.5/presubmit.yml
  modules/grpc_kotlin/1.5.0-rc.5/source.json
  modules/grpc_kotlin/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check, skip-incompatible-flags-test

#5893 Add grpc-java 1.74.0
  modules/grpc-java/1.74.0/MODULE.bazel
  modules/grpc-java/1.74.0/patches/module_dot_bazel.patch
  modules/grpc-java/1.74.0/presubmit.yml
  modules/grpc-java/1.74.0/source.json
  modules/grpc-java/metadata.json
Labels: skip-url-stability-check, skip-incompatible-flags-test

#5872 roaring@4.3.11
  modules/roaring/4.3.11/MODULE.bazel
  modules/roaring/4.3.11/overlay/BUILD.bazel
  modules/roaring/4.3.11/overlay/MODULE.bazel
  modules/roaring/4.3.11/presubmit.yml
  modules/roaring/4.3.11/source.json
  modules/roaring/metadata.json
Labels: skip-url-stability-check

#5909 Add libcpr
  modules/cpr/1.12.0/MODULE.bazel
  modules/cpr/1.12.0/overlay/BUILD.bazel
  modules/cpr/1.12.0/overlay/MODULE.bazel
  modules/cpr/1.12.0/presubmit.yml
  modules/cpr/1.12.0/source.json
  modules/cpr/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check

#5911 protovalidate@1.0.0
  modules/protovalidate/1.0.0/MODULE.bazel
  modules/protovalidate/1.0.0/attestations.json
  modules/protovalidate/1.0.0/presubmit.yml
  modules/protovalidate/1.0.0/source.json
  modules/protovalidate/metadata.json
Labels: skip-incompatible-flags-test

#5903 Publish bazel_bats@0.36.4
  modules/bazel_bats/0.36.4/MODULE.bazel
  modules/bazel_bats/0.36.4/presubmit.yml
  modules/bazel_bats/0.36.4/source.json
  modules/bazel_bats/metadata.json
Labels: presubmit-auto-run, skip-incompatible-flags-test

#5931 Bump gz-plugin to 4.0.0-pre1
  modules/gz-plugin/4.0.0-pre1/MODULE.bazel
  modules/gz-plugin/4.0.0-pre1/patches/module_dot_bazel.patch
  modules/gz-plugin/4.0.0-pre1/presubmit.yml
  modules/gz-plugin/4.0.0-pre1/source.json
  modules/gz-plugin/metadata.json
Labels: skip-url-stability-check

#5956 Publish gotopt2@2.2.0
  modules/gotopt2/2.2.0/MODULE.bazel
  modules/gotopt2/2.2.0/patches/module_dot_bazel_version.patch
  modules/gotopt2/2.2.0/presubmit.yml
  modules/gotopt2/2.2.0/source.json
  modules/gotopt2/metadata.json
Labels: presubmit-auto-run

#5953 bant: 0.2.2 -> 0.2.3
  modules/bant/0.2.3/MODULE.bazel
  modules/bant/0.2.3/presubmit.yml
  modules/bant/0.2.3/source.json
  modules/bant/metadata.json
Labels: presubmit-auto-run

#5958 Publish {rules_img,rules_img_tool}@0.2.2
  modules/rules_img/0.2.2/MODULE.bazel
  modules/rules_img/0.2.2/attestations.json
  modules/rules_img/0.2.2/presubmit.yml
  modules/rules_img/0.2.2/source.json
  modules/rules_img/metadata.json
  modules/rules_img_tool/0.2.2/MODULE.bazel
  modules/rules_img_tool/0.2.2/attestations.json
  modules/rules_img_tool/0.2.2/presubmit.yml
  modules/rules_img_tool/0.2.2/source.json
  modules/rules_img_tool/metadata.json
Labels: skip-incompatible-flags-test

#5932 Bump gz-math to 9.0.0-pre1
  modules/gz-math/9.0.0-pre1/MODULE.bazel
  modules/gz-math/9.0.0-pre1/patches/module_dot_bazel.patch
  modules/gz-math/9.0.0-pre1/presubmit.yml
  modules/gz-math/9.0.0-pre1/source.json
  modules/gz-math/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check

#5933 boost.foreach@1.89.0
  modules/boost.foreach/1.89.0/MODULE.bazel
  modules/boost.foreach/1.89.0/overlay/BUILD.bazel
  modules/boost.foreach/1.89.0/overlay/MODULE.bazel
  modules/boost.foreach/1.89.0/overlay/gen_test_targets.bzl
  modules/boost.foreach/1.89.0/presubmit.yml
  modules/boost.foreach/1.89.0/source.json
  modules/boost.foreach/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check, skip-compatibility-level-check

#5943 Bump gz-sim to 10.0.0-pre1
  modules/gz-sim/10.0.0-pre1/MODULE.bazel
  modules/gz-sim/10.0.0-pre1/patches/module_dot_bazel.patch
  modules/gz-sim/10.0.0-pre1/presubmit.yml
  modules/gz-sim/10.0.0-pre1/source.json
  modules/gz-sim/metadata.json
Labels: skip-url-stability-check

#5977 Publish download_archives@0.1.0
  modules/download_archives/0.1.0/MODULE.bazel
  modules/download_archives/0.1.0/attestations.json
  modules/download_archives/0.1.0/patches/module_dot_bazel_version.patch
  modules/download_archives/0.1.0/presubmit.yml
  modules/download_archives/0.1.0/source.json
  modules/download_archives/metadata.json
Labels: presubmit-auto-run

#5994 Publish container_structure_test 1.20.0
  modules/container_structure_test/1.20.0/MODULE.bazel
  modules/container_structure_test/1.20.0/patches/module_dot_bazel.patch
  modules/container_structure_test/1.20.0/presubmit.yml
  modules/container_structure_test/1.20.0/source.json
  modules/container_structure_test/metadata.json
Labels: skip-url-stability-check

#5976 rules_js_rust_wasm_bindgen@0.0.1
  modules/rules_js_rust_wasm_bindgen/0.0.1/MODULE.bazel
  modules/rules_js_rust_wasm_bindgen/0.0.1/presubmit.yml
  modules/rules_js_rust_wasm_bindgen/0.0.1/source.json
  modules/rules_js_rust_wasm_bindgen/metadata.json
Labels: presubmit-auto-run, skip-incompatible-flags-test

#5991 update cpuinfo to latest version and make it compatible with Bazel 8 platforms
  modules/cpuinfo/0.0.0-20250925-877328f/MODULE.bazel
  modules/cpuinfo/0.0.0-20250925-877328f/overlay/BUILD.bazel
  modules/cpuinfo/0.0.0-20250925-877328f/overlay/MODULE.bazel
  modules/cpuinfo/0.0.0-20250925-877328f/presubmit.yml
  modules/cpuinfo/0.0.0-20250925-877328f/source.json
  modules/cpuinfo/metadata.json
Labels: skip-url-stability-check

#4750 Add nghttp2 module
  modules/nghttp2/1.65.0/MODULE.bazel
  modules/nghttp2/1.65.0/overlay/BUILD.bazel
  modules/nghttp2/1.65.0/overlay/MODULE.bazel
  modules/nghttp2/1.65.0/overlay/config/config.h
  modules/nghttp2/1.65.0/presubmit.yml
  modules/nghttp2/1.65.0/source.json
  modules/nghttp2/metadata.json
Labels: presubmit-auto-run

#6000 update pthreadpool to latest version and make it compatible with Bazel 8 platforms
  modules/pthreadpool/0.0.0-20250926-560c60d/MODULE.bazel
  modules/pthreadpool/0.0.0-20250926-560c60d/patches/module_dot_bazel.patch
  modules/pthreadpool/0.0.0-20250926-560c60d/patches/pthreadpool.patch
  modules/pthreadpool/0.0.0-20250926-560c60d/presubmit.yml
  modules/pthreadpool/0.0.0-20250926-560c60d/source.json
  modules/pthreadpool/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check

#6007 boost.multi_index@1.89.0
  modules/boost.multi_index/1.89.0/MODULE.bazel
  modules/boost.multi_index/1.89.0/overlay/BUILD.bazel
  modules/boost.multi_index/1.89.0/overlay/MODULE.bazel
  modules/boost.multi_index/1.89.0/presubmit.yml
  modules/boost.multi_index/1.89.0/source.json
  modules/boost.multi_index/metadata.json
Labels: skip-url-stability-check, skip-compatibility-level-check

#5990 add libbacktrace
  modules/libbacktrace/1.0.0-20250926-7939218/MODULE.bazel
  modules/libbacktrace/1.0.0-20250926-7939218/overlay/BUILD.bazel
  modules/libbacktrace/1.0.0-20250926-7939218/overlay/MODULE.bazel
  modules/libbacktrace/1.0.0-20250926-7939218/overlay/backtrace-supported.h
  modules/libbacktrace/1.0.0-20250926-7939218/overlay/config.h
  modules/libbacktrace/1.0.0-20250926-7939218/presubmit.yml
  modules/libbacktrace/1.0.0-20250926-7939218/source.json
  modules/libbacktrace/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check

#5983 Replaced uses of `https://ftp.gnu.org/`
  modules/gawk/5.3.2.bcr.2/MODULE.bazel
  modules/gawk/5.3.2.bcr.2/overlay/BUILD.bazel
  modules/gawk/5.3.2.bcr.2/overlay/MODULE.bazel
  modules/gawk/5.3.2.bcr.2/overlay/posix/config_darwin.h
  modules/gawk/5.3.2.bcr.2/overlay/posix/config_linux.h
  modules/gawk/5.3.2.bcr.2/overlay/test/BUILD.bazel
  modules/gawk/5.3.2.bcr.2/presubmit.yml
  modules/gawk/5.3.2.bcr.2/source.json
  modules/gawk/metadata.json
  modules/ncurses/6.4.20221231.bcr.9/MODULE.bazel
  modules/ncurses/6.4.20221231.bcr.9/overlay/BUILD.bazel
  modules/ncurses/6.4.20221231.bcr.9/overlay/MODULE.bazel
  modules/ncurses/6.4.20221231.bcr.9/overlay/bazel/BUILD.bazel
  modules/ncurses/6.4.20221231.bcr.9/overlay/bazel/automake_substitution.bzl
  modules/ncurses/6.4.20221231.bcr.9/overlay/bazel/pseudo_configure.bzl
  modules/ncurses/6.4.20221231.bcr.9/overlay/bazel/terminfo.bzl
  modules/ncurses/6.4.20221231.bcr.9/patches/change_mode.patch
  modules/ncurses/6.4.20221231.bcr.9/patches/fail_on_error.patch
  modules/ncurses/6.4.20221231.bcr.9/presubmit.yml
  modules/ncurses/6.4.20221231.bcr.9/source.json
  modules/ncurses/metadata.json
  modules/readline/8.2.bcr.3/MODULE.bazel
  modules/readline/8.2.bcr.3/overlay/BUILD.bazel
  modules/readline/8.2.bcr.3/overlay/MODULE.bazel
  modules/readline/8.2.bcr.3/presubmit.yml
  modules/readline/8.2.bcr.3/source.json
  modules/readline/metadata.json
  modules/sed/4.9.bcr.3/MODULE.bazel
  modules/sed/4.9.bcr.3/overlay/BUILD.bazel
  modules/sed/4.9.bcr.3/overlay/MODULE.bazel
  modules/sed/4.9.bcr.3/overlay/config_linux.bzl
  modules/sed/4.9.bcr.3/overlay/config_linux.h
  modules/sed/4.9.bcr.3/overlay/config_macos.bzl
  modules/sed/4.9.bcr.3/overlay/config_macos.h
  modules/sed/4.9.bcr.3/overlay/inline.bat
  modules/sed/4.9.bcr.3/overlay/inline.sh
  modules/sed/4.9.bcr.3/presubmit.yml
  modules/sed/4.9.bcr.3/source.json
  modules/sed/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check

#5980 abc@0.0.0-20250903-yosyshq
  modules/abc/0.0.0-20250408-yosyshq.bcr.2/MODULE.bazel
  modules/abc/0.0.0-20250408-yosyshq.bcr.2/overlay/BUILD.bazel
  modules/abc/0.0.0-20250408-yosyshq.bcr.2/overlay/MODULE.bazel
  modules/abc/0.0.0-20250408-yosyshq.bcr.2/presubmit.yml
  modules/abc/0.0.0-20250408-yosyshq.bcr.2/source.json
  modules/abc/0.0.0-20250903-yosyshq/MODULE.bazel
  modules/abc/0.0.0-20250903-yosyshq/overlay/BUILD.bazel
  modules/abc/0.0.0-20250903-yosyshq/overlay/MODULE.bazel
  modules/abc/0.0.0-20250903-yosyshq/presubmit.yml
  modules/abc/0.0.0-20250903-yosyshq/source.json
  modules/abc/metadata.json
Labels: skip-url-stability-check

#5999 scip: Add 9.2.3
  modules/scip/9.2.3/MODULE.bazel
  modules/scip/9.2.3/overlay/BUILD.bazel
  modules/scip/9.2.3/overlay/MODULE.bazel
  modules/scip/9.2.3/patches/add_buildflags_h.patch
  modules/scip/9.2.3/patches/add_config_h.patch
  modules/scip/9.2.3/patches/add_githash_c.patch
  modules/scip/9.2.3/patches/add_scip_export_h.patch
  modules/scip/9.2.3/patches/compute_symmetry_bliss.cpp.patch
  modules/scip/9.2.3/presubmit.yml
  modules/scip/9.2.3/source.json
  modules/scip/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check

#5979 or-tools: add 9.13 and 9.14
  modules/or-tools/9.13/MODULE.bazel
  modules/or-tools/9.13/patches/bazel.patch
  modules/or-tools/9.13/presubmit.yml
  modules/or-tools/9.13/source.json
  modules/or-tools/9.14/MODULE.bazel
  modules/or-tools/9.14/patches/bazel.patch
  modules/or-tools/9.14/presubmit.yml
  modules/or-tools/9.14/source.json
  modules/or-tools/metadata.json
Labels: presubmit-auto-run, skip-incompatible-flags-test

#6039 Publish {rules_img,rules_img_tool}@0.2.4
  modules/rules_img/0.2.4/MODULE.bazel
  modules/rules_img/0.2.4/attestations.json
  modules/rules_img/0.2.4/presubmit.yml
  modules/rules_img/0.2.4/source.json
  modules/rules_img/metadata.json
  modules/rules_img_tool/0.2.4/MODULE.bazel
  modules/rules_img_tool/0.2.4/attestations.json
  modules/rules_img_tool/0.2.4/presubmit.yml
  modules/rules_img_tool/0.2.4/source.json
  modules/rules_img_tool/metadata.json
Labels: skip-incompatible-flags-test

#6017 Add tcmalloc@0.0.0-20250927-12f2552
  modules/tcmalloc/0.0.0-20250927-12f2552/MODULE.bazel
  modules/tcmalloc/0.0.0-20250927-12f2552/patches/0001-Add-MODULE.bazel.patch
  modules/tcmalloc/0.0.0-20250927-12f2552/presubmit.yml
  modules/tcmalloc/0.0.0-20250927-12f2552/source.json
  modules/tcmalloc/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check

#6050 Publish portable_cc_toolchain@2025.09.29
  modules/portable_cc_toolchain/2025.09.29/MODULE.bazel
  modules/portable_cc_toolchain/2025.09.29/attestations.json
  modules/portable_cc_toolchain/2025.09.29/patches/module_dot_bazel_version.patch
  modules/portable_cc_toolchain/2025.09.29/presubmit.yml
  modules/portable_cc_toolchain/2025.09.29/source.json
  modules/portable_cc_toolchain/metadata.json
Labels: auto-merged

#5982 bison@3.8.2, flex@2.6.4
  modules/bison/3.8.2/MODULE.bazel
  modules/bison/3.8.2/overlay/BUILD.bazel
  modules/bison/3.8.2/overlay/MODULE.bazel
  modules/bison/3.8.2/overlay/bison_utils.bzl
  modules/bison/3.8.2/overlay/config_linux.bzl
  modules/bison/3.8.2/overlay/config_linux.h
  modules/bison/3.8.2/overlay/config_macos.bzl
  modules/bison/3.8.2/overlay/config_macos.h
  modules/bison/3.8.2/overlay/src/bazel_runfiles.cc
  modules/bison/3.8.2/patches/bison_runfiles.patch
  modules/bison/3.8.2/presubmit.yml
  modules/bison/3.8.2/source.json
  modules/bison/README.md
  modules/bison/generate_bison_config_bzl.py
  modules/bison/metadata.json
  modules/flex/2.6.4/MODULE.bazel
  modules/flex/2.6.4/overlay/BUILD.bazel
  modules/flex/2.6.4/overlay/MODULE.bazel
  modules/flex/2.6.4/patches/hardcode_int_max_log10.patch
  modules/flex/2.6.4/presubmit.yml
  modules/flex/2.6.4/source.json
  modules/flex/metadata.json
Labels: presubmit-auto-run

#6055 mcap@2.0.2
  modules/mcap/2.0.2/MODULE.bazel
  modules/mcap/2.0.2/overlay/BUILD.bazel
  modules/mcap/2.0.2/overlay/MODULE.bazel
  modules/mcap/2.0.2/presubmit.yml
  modules/mcap/2.0.2/source.json
  modules/mcap/metadata.json
Labels: skip-url-stability-check

#5779 libxau@1.0.12.bcr.2, libxcb@1.17.0.bcr.2, libxtrans@1.5.2.bcr.1, libx11@1.8.12.bcr.2
  modules/libx11/1.8.12.bcr.2/MODULE.bazel
  modules/libx11/1.8.12.bcr.2/overlay/BUILD.bazel
  modules/libx11/1.8.12.bcr.2/overlay/MODULE.bazel
  modules/libx11/1.8.12.bcr.2/overlay/src/config.h.in
  modules/libx11/1.8.12.bcr.2/presubmit.yml
  modules/libx11/1.8.12.bcr.2/source.json
  modules/libx11/metadata.json
  modules/libxau/1.0.12.bcr.2/MODULE.bazel
  modules/libxau/1.0.12.bcr.2/overlay/BUILD.bazel
  modules/libxau/1.0.12.bcr.2/overlay/MODULE.bazel
  modules/libxau/1.0.12.bcr.2/presubmit.yml
  modules/libxau/1.0.12.bcr.2/source.json
  modules/libxau/metadata.json
  modules/libxcb/1.17.0.bcr.2/MODULE.bazel
  modules/libxcb/1.17.0.bcr.2/overlay/BUILD.bazel
  modules/libxcb/1.17.0.bcr.2/overlay/MODULE.bazel
  modules/libxcb/1.17.0.bcr.2/overlay/src/config.h.in
  modules/libxcb/1.17.0.bcr.2/presubmit.yml
  modules/libxcb/1.17.0.bcr.2/source.json
  modules/libxcb/metadata.json
  modules/libxtrans/1.5.2.bcr.1/MODULE.bazel
  modules/libxtrans/1.5.2.bcr.1/overlay/BUILD.bazel
  modules/libxtrans/1.5.2.bcr.1/overlay/MODULE.bazel
  modules/libxtrans/1.5.2.bcr.1/presubmit.yml
  modules/libxtrans/1.5.2.bcr.1/source.json
  modules/libxtrans/metadata.json
Labels: skip-url-stability-check
