Repository bazelbuild/bazel-central-registry, pull requests merged in 2025-10, with the labels that each got.

#6062 tcl_lang@8.6.16.bcr.1, abc@0.0.0-20250903-yosyshq.bcr.1
  modules/abc/0.0.0-20250903-yosyshq.bcr.1/MODULE.bazel
  modules/abc/0.0.0-20250903-yosyshq.bcr.1/overlay/BUILD.bazel
  modules/abc/0.0.0-20250903-yosyshq.bcr.1/overlay/MODULE.bazel
  modules/abc/0.0.0-20250903-yosyshq.bcr.1/presubmit.yml
  modules/abc/0.0.0-20250903-yosyshq.bcr.1/source.json
  modules/abc/metadata.json
  modules/tcl_lang/8.6.16.bcr.1/MODULE.bazel
  modules/tcl_lang/8.6.16.bcr.1/overlay/BUILD.bazel
  modules/tcl_lang/8.6.16.bcr.1/overlay/MODULE.bazel
  modules/tcl_lang/8.6.16.bcr.1/overlay/tclConfig_macos.h
  modules/tcl_lang/8.6.16.bcr.1/overlay/tclConfig_unix.h
  modules/tcl_lang/8.6.16.bcr.1/overlay/tclConfig_windows.h
  modules/tcl_lang/8.6.16.bcr.1/presubmit.yml
  modules/tcl_lang/8.6.16.bcr.1/source.json
  modules/tcl_lang/9.0.2.bcr.1/MODULE.bazel
  modules/tcl_lang/9.0.2.bcr.1/overlay/BUILD.bazel
  modules/tcl_lang/9.0.2.bcr.1/overlay/MODULE.bazel
  modules/tcl_lang/9.0.2.bcr.1/overlay/tclConfig_macos.h
  modules/tcl_lang/9.0.2.bcr.1/overlay/tclConfig_unix.h
  modules/tcl_lang/9.0.2.bcr.1/overlay/tclConfig_windows.h
  modules/tcl_lang/9.0.2.bcr.1/presubmit.yml
  modules/tcl_lang/9.0.2.bcr.1/source.json
  modules/tcl_lang/metadata.json
Labels: skip-url-stability-check

#6071 rules_perl@0.4.3
  modules/rules_perl/0.4.3/MODULE.bazel
  modules/rules_perl/0.4.3/patches/module_dot_bazel.patch
  modules/rules_perl/0.4.3/presubmit.yml
  modules/rules_perl/0.4.3/source.json
  modules/rules_perl/metadata.json
Labels: skip-url-stability-check

#6073 Publish rules_shtk-1.7.1
  modules/rules_shtk/1.7.1/MODULE.bazel
  modules/rules_shtk/1.7.1/presubmit.yml
  modules/rules_shtk/1.7.1/source.json
  modules/rules_shtk/metadata.json
Labels: presubmit-auto-run

#6080 xtensor@0.27.1
  modules/xtensor/0.27.1/MODULE.bazel
  modules/xtensor/0.27.1/overlay/BUILD.bazel
  modules/xtensor/0.27.1/overlay/MODULE.bazel
  modules/xtensor/0.27.1/presubmit.yml
  modules/xtensor/0.27.1/source.json
  modules/xtensor/metadata.json
Labels: skip-url-stability-check

#6081 tar.bzl@0.6.0
  modules/tar.bzl/0.6.0/MODULE.bazel
  modules/tar.bzl/0.6.0/attestations.json
  modules/tar.bzl/0.6.0/patches/module_dot_bazel_version.patch
  modules/tar.bzl/0.6.0/presubmit.yml
  modules/tar.bzl/0.6.0/source.json
  modules/tar.bzl/metadata.json
Labels: auto-merged

#6083 catch2@3.11.0
  modules/catch2/3.11.0/MODULE.bazel
  modules/catch2/3.11.0/overlay/MODULE.bazel
  modules/catch2/3.11.0/presubmit.yml
  modules/catch2/3.11.0/source.json
  modules/catch2/metadata.json
Labels: skip-url-stability-check, auto-merged

#6086 javaparser@3.27.0
  modules/javaparser/3.27.0/MODULE.bazel
  modules/javaparser/3.27.0/overlay/BUILD.bazel
  modules/javaparser/3.27.0/overlay/MODULE.bazel
  modules/javaparser/3.27.0/overlay/javaparser-core/BUILD.bazel
  modules/javaparser/3.27.0/overlay/javaparser-core/build.bzl
  modules/javaparser/3.27.0/presubmit.yml
  modules/javaparser/3.27.0/source.json
  modules/javaparser/metadata.json
Labels: presubmit-auto-run, skip-url-stability-check

#6085 bazel_lib@3.0.0-rc.0
  modules/bazel_lib/3.0.0-rc.0/MODULE.bazel
  modules/bazel_lib/3.0.0-rc.0/attestations.json
  modules/bazel_lib/3.0.0-rc.0/patches/go_dev_dep.patch
  modules/bazel_lib/3.0.0-rc.0/patches/module_dot_bazel_version.patch
  modules/bazel_lib/3.0.0-rc.0/presubmit.yml
  modules/bazel_lib/3.0.0-rc.0/source.json
  modules/bazel_lib/metadata.json
Labels: presubmit-auto-run

#6090 Yank LZ4 1.10.0
  modules/lz4/metadata.json
Labels: presubmit-auto-run

#6006 Add Eigen 5.0.0
  modules/eigen/5.0.0/MODULE.bazel
  modules/eigen/5.0.0/overlay/BUILD.bazel
  modules/eigen/5.0.0/overlay/MODULE.bazel
  modules/eigen/5.0.0/presubmit.yml
  modules/eigen/5.0.0/source.json
  modules/eigen/metadata.json
Labels: skip-url-stability-check

#6115 closure-templates@1.0.1
  modules/closure-templates/1.0.1/MODULE.bazel
  modules/closure-templates/1.0.1/attestations.json
  modules/closure-templates/1.0.1/patches/module_dot_bazel_version.patch
  modules/closure-templates/1.0.1/presubmit.yml
  modules/closure-templates/1.0.1/source.json
  modules/closure-templates/metadata.json
Labels: presubmit-auto-run
